apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: camunda-vs
  namespace: camunda
spec:
  hosts:
    - camunda-dev.example.com        # <-- change to your domain
  gateways:
    - camunda-gateway
  http:
    # -------------------------------------------------------
    # 1. Keycloak (OIDC)
    # Everything under /auth goes to identity-keycloak
    # -------------------------------------------------------
    - match:
        - uri:
            prefix: /auth
      route:
        - destination:
            host: camunda-identity-keycloak.camunda.svc.cluster.local
            port:
              number: 8080

    # -------------------------------------------------------
    # 2. Management Identity (used by Web Modeler for login)
    # -------------------------------------------------------
    - match:
        - uri:
            prefix: /identity
      route:
        - destination:
            host: camunda-identity.camunda.svc.cluster.local
            port:
              number: 8080

    # -------------------------------------------------------
    # 3. Web Modeler (UI + backend API)
    # -------------------------------------------------------
    - match:
        - uri:
            prefix: /modeler
      route:
        - destination:
            host: camunda-web-modeler.camunda.svc.cluster.local
            port:
              number: 80  # or 8080 depending on service
